# Generated by Django 4.2 on 2026-06-17 12:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AI_toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy_name', models.CharField(max_length=100)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('order_qty', models.CharField(max_length=100)),
                ('old_price', models.CharField(max_length=10)),
                ('new_price', models.CharField(max_length=10)),
                ('offer', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Anime_toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy_name', models.CharField(max_length=100)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('order_qty', models.CharField(max_length=100)),
                ('old_price', models.CharField(max_length=10)),
                ('new_price', models.CharField(max_length=10)),
                ('offer', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('qty', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy_name', models.CharField(max_length=100)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('order_qty', models.CharField(max_length=100)),
                ('old_price', models.CharField(max_length=10)),
                ('new_price', models.CharField(max_length=10)),
                ('offer', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=1200)),
                ('category', models.CharField(choices=[('sports', 'Sports Toys'), ('ai', 'AI Toys'), ('sleeping', 'Sleeping Toys'), ('anime', 'Anime Toys'), ('robotic', 'Robotic Toys')], default='sports', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_photo', models.FileField(blank=True, null=True, upload_to='photo/')),
                ('order_quantity', models.CharField(max_length=100)),
                ('user_quantity', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(default='Confirmed', max_length=50)),
                ('action_status', models.CharField(blank=True, choices=[('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('combo_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Robotic_toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy_name', models.CharField(max_length=100)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('order_qty', models.CharField(max_length=100)),
                ('old_price', models.CharField(max_length=10)),
                ('new_price', models.CharField(max_length=10)),
                ('offer', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sleeping_toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy_name', models.CharField(max_length=100)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('order_qty', models.CharField(max_length=100)),
                ('old_price', models.CharField(max_length=10)),
                ('new_price', models.CharField(max_length=10)),
                ('offer', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sports_toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy_name', models.CharField(max_length=100)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('order_qty', models.CharField(max_length=100)),
                ('old_price', models.CharField(max_length=10)),
                ('new_price', models.CharField(max_length=10)),
                ('offer', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kabi2026.kyc')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='kabi2026.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kabi2026.kyc')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kabi2026.items')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kabi2026.items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kabi2026.kyc')),
            ],
        ),
    ]
