# Generated by Django 4.2 on 2026-06-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabi2026', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AI_toys',
        ),
        migrations.DeleteModel(
            name='Anime_toys',
        ),
        migrations.DeleteModel(
            name='Robotic_toys',
        ),
        migrations.DeleteModel(
            name='Sleeping_toys',
        ),
        migrations.DeleteModel(
            name='sports_toys',
        ),
    ]
