# Generated by Django 4.2 on 2026-06-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabi2026', '0002_delete_ai_toys_delete_anime_toys_delete_robotic_toys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
