from django.urls import path
from . import views

urlpatterns = [
    path('logout',views.logout_user,name='logout'),
    path('user_login', views.user_login, name='user_login'),
    path('admin_page', views.admin_page, name='admin_page'),
    path('', views.user_home, name='user_home'),
    path('view_item/<int:id>/', views.view_item, name='view_item'),
    path('order_input_get_from_user/<int:id>/',views.order_input_get_from_user,name='order_input_get_from_user'),
    path('confirming_order/<int:id>/', views.confirming_order, name='confirming_order'),
    path('orders_view_by_admin', views.orders_view_by_admin,name='orders_view_by_admin'),
    path('admin_home',views.admin_home,name='admin_home'),
    path('user_personal_information_type_by_user',views.user_personal_information_type_by_user,name='user_personal_information_type_by_user'),
    path('view_users_by_admin',views.view_users_by_admin,name='view_users_by_admin'),
    path('update_user_personal/<int:id>/', views.update_user_personal, name='update_user_personal'),
    path('view_user_personal_by_user/<int:id>/',views.view_user_personal_by_user,name='view_user_personal_by_user'),
    path('update_items/<int:id>/',views.update_items,name='update_items'),
    path('delete_item/<int:id>/',views.delete_item,name='delete_item'),
    path('view_item_by_admin/<int:id>/',views.view_item_by_admin,name='view_item_by_admin'),
    path('category/<str:category_name>/', views.view_toys_by_category, name='view_toys_by_category'),
    path('view_orders_by_user',views.user_order_view_by_user,name='user_order_view_by_user'),
    path('update_order_status/<int:id>/<str:status>/', views.update_order_status, name='update_order_status'),
    path('cancel_order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('return_order/<int:order_id>/', views.return_order, name='return_order'),
    path('ordered_user_details/<int:id>/',views.ordered_user_details,name='ordered_user_details'),
    path('view_carts_by_user',views.view_carts_by_user,name='view_carts_by_user'),
    path('admin_category/<str:category_name>/', views.view_toys_by_category_admin, name='view_toys_by_category_admin'),
    path ('wallet_system_for_user',views.wallet_system_for_user,name="wallet_system_for_user"),
#    path("admin-dashboard/",views.admin_dashboard,name="admin_dashboard"),
    path('copy-item/<int:item_id>/', views.copy_item_to_orders, name='copy_item_to_orders'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('view_carts_by_user', views.view_carts_by_user, name='view_carts_by_user'),
    path('increase_qty/<int:cart_id>/', views.increase_qty, name='increase_qty'),
    path('decrease_qty/<int:cart_id>/', views.decrease_qty, name='decrease_qty'),
    path('remove_cart/<int:cart_id>/', views.remove_cart, name='remove_cart'),
    path('cart_checkout/', views.cart_checkout, name='cart_checkout'),
    path('conversation/<int:product_id>/<int:user_id>/',views.conversation_user,name='conversation_user'),
    path('admin_reply/<int:product_id>/<int:user_id>/',views.admin_reply,name='admin_reply'),
    path('admin_chat_list/',views.admin_chat_list,name='admin_chat_lists'),
    path('user_chat_lists',views.user_chat_lists,name='user_chat_lists'),
    path('submit_rating/<int:order_id>/', views.submit_product_rating, name='submit_product_rating'),
    path('admin_reviews/', views.admin_reviews_list, name='admin_reviews_list'),
    path('admin/returned-orders/', views.admin_returned_products_view, name='admin_returned_orders'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('admin_logout/', views.admin_logout, name='admin_logout'),
]